# Generated by Django 2.2.2 on 2019-08-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('pkid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Departmentfloormap',
            fields=[
                ('pkid', models.AutoField(primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(max_length=40)),
                ('num_of_users', models.IntegerField(max_length=40)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_floor', to='restservice.Departments')),
            ],
        ),
    ]
