# Generated by Django 2.2.2 on 2019-08-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentfloormap',
            name='floor_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departmentfloormap',
            name='num_of_users',
            field=models.IntegerField(),
        ),
    ]
